### ISSUE TITLE
pug-lint executable broken

### ISSUE THREAD

**Issue by pykong** [benedfit/SublimeLinter-contrib-jade-lint#10]
Currently, SublimeLinter-pug-lint is defunct, as no line annotations are being displayed.
The executable is found and called but exits with code 2. Changing `error_stream = util.STREAM_STDERR` ow captures output.

While I initially thought this problem due to incompatibility with `SL4` I was able to trace it back to the `pug-lint` executable itself. I have subsequently filed an issue: https://github.com/pugjs/pug-lint/issues/164

Can anyone confirm this behavior?

`SL-pug-lint`: 1.2.0
`pug-lint`: 2.5.0
ST3: 3208
Linux Mint 19.1

**Comment by Edditoria** [comment]
Hi,

If I understand correctly, this is an error that SublimeLinter panel doesn't show anything.

I think it is fixed in v2. Consider this issue solved.

If you have problem or question, please feel free to discuss here.

**Comment by braver** [comment]
🎉
