### ISSUE TITLE
Support vue syntax?

### ISSUE THREAD

**Issue by trainiac** [benedfit/SublimeLinter-contrib-jade-lint#5]
Thanks for this plugin.

**Problem:** I want SublimeLinter to lint the pug section of my .vue file (syntax for vuejs components). But since the linter plugin only lints a set supported syntaxes as indicated here https://github.com/benedfit/SublimeLinter-contrib-pug-lint/blob/master/linter.py#L20 SublimeLinter won't end up running.  

**Possible Solutions:**

1) Try to map my vue syntax to jade or pug.  This won't work because I actually want eslint, stylelint, and puglint to all run when I hit save and the `syntax_map` config in SublimeLinter settings won't only allows a one to one mapping of syntax.

2) Fork this repo and release a new package that supports the vue syntax.

3) Extend or override the syntax property of the a linter plugin.

1 Won't work. 2 seems like a bad solution. 3 is clearly preferable. Is there any way to do this? Or perhaps there is some other way to achieve what I want?

Thanks

**Comment by pykong** [comment]
AFAIK we support linting embedded syntaxes. Like javascript inside HTML for example.
I will investigate once #10 is solved.

**Comment by Edditoria** [comment]
Hi @trainiac ,

I had similar problem about vue components and pushed some fixes on March.

Would you test it out if you still use Sublime, Vue and Pug?

I'm relatively new in this repo. Hope that I can solve your problem. :)

**Comment by Edditoria** [comment]
It seems work fine in <*.vue> files. I would consider to close this issue. Fixed in #13 .
