### ISSUE TITLE
I have installed plugin to Sublime Text 3, but nothing appear in the tools menu.

### ISSUE THREAD

**Issue by SilentImp** [benedfit/SublimeLinter-contrib-jade-lint#6]
Hi,
I have installed plugin to Sublime Text 3 (build 3126), but nothing appear in the tools menu.
How I could actually use it?

**Comment by pykong** [comment]
@SilentImp 
1. Install `SublimeLinter`
2. Install `SublimeLinter-pug-lint`
3. Install `pug-lint` itself via npm

Now any pug file will receive linting.
See: http://www.sublimelinter.com/en/stable/installation.html

Be aware that right now there seems to be an issue with `pug-lint` itself: #10 

I am closing this right now. Feel free to comment if you happen to have any further questions.
