### ISSUE TITLE
SublimeLinter 4 has breaking API changes

### ISSUE THREAD

**Issue by braver** [benedfit/SublimeLinter-contrib-jade-lint#7]
We're making big changes to SublimeLinter and some of it will break our interface with this particular plugin. You can have a look this change for how to prepare for this change:

https://github.com/SublimeLinter/SublimeLinter-phpmd/commit/ae3070586096114467c65d052f68ba872f2adc4b

**Comment by pykong** [comment]
Changes appear to have been implemented.
See: https://github.com/SublimeLinter/SublimeLinter-pug-lint/commit/fc23037765aef38ae12a5810a898dfec2cac7b53

Hence I am closing this.

Be aware of #10 though.
